### ISSUE TITLE
Thermostat Card Clipping

### ISSUE THREAD

**Issue by kflinderman** [home-assistant/ui-schema#221]
Hello,

I just wanted to point out that the thermostat card does not play well in a horizontal stack with any small browser window (really mobile is where I see it the most).  Just feel like at least it should not clip out the bottom buttons but should still be able to be stacked horizontally.  Doesn't make sense for this to be one of the exceptions.

https://imgur.com/a/nPr24VH

**Comment by ZenDIY** [comment]
Hello,
I am facing the same issue reported by @kflinderman. The thermostat card is OK when the smartphone is in vertical position, but when I rotate my smartphone the card seems to be clipped and bottom icons/commands disappears.

![mobile_horizontal](https://user-images.githubusercontent.com/25845078/51029324-4ba6a180-1596-11e9-8892-a2802427b6c0.png)
![mobile_vertical](https://user-images.githubusercontent.com/25845078/51029325-4ba6a180-1596-11e9-8292-be61feb7482d.png)

**Comment by iantrich** [comment]
This is fixed now, I believe

**Comment by kflinderman** [comment]
It is much better than it used to be.  I still get a slight clipping on the bottom for a normal window.  But I can also really screw with it if the window gets tiny.  Not sure if that should be looked at or not, cause I really had to make it small to get there.  Here are the two pictures I took, the first one is what I see on mobile, the second is what I got to look wonky.

https://imgur.com/cZ15iPr
https://imgur.com/DY9BReL

**Comment by Misiu** [comment]
Unfortunately, there are still issues with the thermostat card.

 ![image](https://user-images.githubusercontent.com/1741838/63983509-50897880-cac7-11e9-9423-7c515c60ab1f.png)

The config I have is really simple:

```
type: vertical-stack
cards:
  - cards:
      - entity: climate.study
        type: thermostat
        name: Kuchnia
      - entity: climate.study
        type: thermostat
        name: Sypialnia
    type: horizontal-stack
  - cards:
      - entity: climate.study
        type: thermostat
        name: Pokój dzienny
      - entity: climate.study
        type: thermostat
        name: Korytarz
    type: horizontal-stack
```

When You have 2x2 grid with thermostats it looks quite good on PC (Win10 Chrome 76), but on mobile, it looks terrible:
![image](https://user-images.githubusercontent.com/1741838/63983919-305ab900-cac9-11e9-8f2e-70b856af1f50.png)

is there a chance to fix the cropping issue? Also, can the thermostat card adjust font size based on its size?
I manually changed the font size in cards and it looks much better (two bottom left cards):
![image](https://user-images.githubusercontent.com/1741838/63984209-6a788a80-caca-11e9-9884-c7d567d497cb.png)

@iantrich  Can the font size be dynamic? Based on card size?

**Comment by skilly00** [comment]
Any update on this issue?

**Comment by Misiu** [comment]
@iantrich font isn't the only issue. here is also unneeded padding for `modes` class when ha-card has `small` class. This should be a very simple fix -quick-change in CSS rules.

**Comment by iantrich** [comment]
PRs welcome 😁

**Comment by Misiu** [comment]
I'd like to help, but I use Windows and from all the descriptions it is hard to get frontend development up and running on Windows.

Padding can be easily solved by replacing this line: https://github.com/home-assistant/home-assistant-polymer/blob/dev/src/panels/lovelace/cards/hui-thermostat-card.ts#L558
so instead:
```
.modes {
  margin-top: 16px;
}
```
You will have:
```
.large .modes {
  margin-top: 16px;
}
```

this way padding will be added only to large view.

I'm not sure about font-size, because it would be better to change that in the code and then look at demo site.

**Comment by iantrich** [comment]
@Misiu I used to do HA frontend work on Windows. The easy way to do that is to install [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10).
You could also do it in a virtual machine or dual boot to Linux.

I currently have dual boot setup on my PC. Linux is free and easy to setup and makes dev work a breeze, so highly recommend it to anyone. You can PM me on Discord if you want to dive into it.

**Comment by Misiu** [comment]
@iantrich thank for offering help.
Give me some time, I have a deadline on a project (that involves Home Assistant). When I finish it I'll have some free time so we can get back to this then. I need roughly one, maybe two weeks.
